### ISSUE TITLE
CheckboxGroup issue on Safari

### ISSUE THREAD

**Issue by AlexandreBonaventure** [JosephusPaye/Keen-UI#274] opened 2017-03-07 23:02 UTC
Safari Version 10.0.3 (10602.4.8.0.1)
see https://josephuspaye.github.io/Keen-UI/#/ui-checkbox-group

---
CheckboxGroup aren't responding to click.
However, Checkbox component is working as expected.

I don't have the time to diagnose the problem for now, so can't tell you more about it.
Thanks.

**Comment by JosephusPaye** [comment] 2017-04-07 22:49
Thanks for the report. Can someone else using Safari confirm this?

**Comment by reinvanmeeteren** [comment] 2017-05-03 13:33
We have the same issue. This bug causes the UiCheckboxGroup to not function on Safari browser (also not on mobile/cordova). I tracked down the cause to the order of events being different on Safari (first the change event is fired and then the click event).

With the following change it works as expected: #325

**Comment by chenqiushi** [comment] 2017-05-18 14:30
The components does not work well on PC Safari (v8.0.3)browser. Visit the demo site: [https://josephuspaye.github.io/Keen-UI/1.0.0/](https://josephuspaye.github.io/Keen-UI/1.0.0/)， both version are not ok. Could you please focus on this problem. Thanks

**Comment by JosephusPaye** [comment] 2019-01-27 08:18
Fixed in https://github.com/JosephusPaye/Keen-UI/pull/325.

**Comment by JosephusPaye** [comment] 2019-01-28 10:56
Fix released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).

**Closed by JosephusPaye** 2019-01-28 10:56 UTC
Labels: fixed
