### ISSUE TITLE
UI-Select  multiple bug

### ISSUE THREAD

**Issue by xiaolongyuan** [JosephusPaye/Keen-UI#109] opened 2016-08-02 08:26 UTC
```
         <ui-select
                  label="店铺分类" name="select-cat-2" placeholder="请选择店铺分类"
                  show-search multiple
                  :options="shopcatsSelect" :value.sync="form.shopCategorys"
          ></ui-select>
```

```
 data(){
  return {
    form:{ shopCategorys : [ {text:'早春外套',value:10001}  ] }
  }
 }
```

![image](https://cloud.githubusercontent.com/assets/3142363/17321924/8d695d5c-58cd-11e6-965b-a6dd8da8a165.png)

![image](https://cloud.githubusercontent.com/assets/3142363/17321912/800426ce-58cd-11e6-81ab-589cf1b40e27.png)

![image](https://cloud.githubusercontent.com/assets/3142363/17321967/c7b78790-58cd-11e6-95bd-965bf3761b99.png)

**Comment by JosephusPaye** [comment] 2016-08-04 12:00
I don't understand what the problem is, could you clarify?

**Comment by EmilMoe** [comment] 2016-08-05 22:16
It's probably related: https://github.com/JosephusPaye/Keen-UI/issues/110

**Comment by JosephusPaye** [comment] 2016-08-06 09:20
Closing for now. Provide more details if you still have an issue.

**Closed by JosephusPaye** 2016-08-06 09:20 UTC

**Comment by Birssan** [comment] 2017-02-27 14:41
I have the same issue here with the last version of KeenUI.
To explain what's in the screenshots, when you use v-model to pre-select defaults values for multiple select, these values are displayed in the input, but not checked in the list.
When you select them in the list, they are displayed twice in the input, first time as the default values, and the second time when checked...
