### ISSUE TITLE
UICollapsible wont expand properly

### ISSUE THREAD

**Issue by jjsquad** [JosephusPaye/Keen-UI#111] opened 2016-08-03 18:06 UTC
Hi!

I think that is a bug... but
When I load a dynamic content into a UiCollapsible, this wont expand to reveal all itens into then.

Sorry for my bad english!
TY

**Comment by citycide** [comment] 2016-08-03 23:47
This should actually be resolved with the next release. I had the same issue and solved it with PR #101. It's already merged but hasn't been cut into a release yet.

If your issue is different, try to put together an example that shows the problem. There's a [codepen template](http://codepen.io/pen?template=NrKmPQ) you can use.

@JosephusPaye potential duplicate of #97

**Comment by citycide** [comment] 2016-08-04 00:20
@jjsquad Also, you might just need to refresh the height of the collapsible.

```javascript
const app = new Vue(/* ... */)

app.$nextTick(() => {
  app.$broadcast('ui-collapsible::refresh-height')
})
```

or if you only want to refresh the height of a specific collapsible:

```javascript
app.$nextTick(() => {
  app.$broadcast('ui-collapsible::refresh-height', 'id-of-collapsible')
})
```

This should work in most cases and my PR hopefully solves the situations where it doesn't.

**Comment by jjsquad** [comment] 2016-08-04 06:12
Thank you @citycide. The problem its with style into component that fixes the height property.

Waiting for update fixing this.
Cya!

**Closed** 2016-08-04 06:12 UTC
