### ISSUE TITLE
UiCheckbox in IE inverse value

### ISSUE THREAD

**Issue by Thijs5** [JosephusPaye/Keen-UI#239] opened 2017-02-13 14:29 UTC
When using Internet Explorer the checkbox' value doesn't get updated correctly when toggling. Only when clicking a second time on a checkbox the internal value gets updated to the previous value.

The same problem is in the checkbox component.

I've added a gif to demonstrate the problem. This is taken using IE 11.0.900.18538 on Windows 8.1 using the documentation pages.

![bug-keen-ui](https://cloud.githubusercontent.com/assets/1286325/22887087/0348c1bc-f201-11e6-81d5-10a13ed855a8.gif)

**Comment by JosephusPaye** [comment] 2017-02-19 12:30
Hi @Thijs5,

This is a bug I notice some times when using IE, but can't seem to find the cause as it doesn't always happen (for me).

Suggestions here will be appreciated.

**Comment by JosephusPaye** [comment] 2017-02-27 01:39
This is due to an IE issue. See https://github.com/vuejs/vue/issues/4796.

Should be fixed by upgrading to [Vue 2.2](https://github.com/vuejs/vue/releases/tag/v2.2.0).

**Comment by JosephusPaye** [comment] 2017-09-02 02:08
Re-open if there's still an issue.

**Comment by doccom-applibs** [comment] 2018-03-27 12:18
@JosephusPaye Still seeing this issue in Edge - Vue 2.5

**Comment by Sethles** [comment] 2018-06-12 09:10
Yip, still seeing this issue in Edge - Vue 2.5

**Comment by shinsenter** [comment] 2018-12-18 06:37
Still seeing this issue in IE and Edge. Using Vue 2.5.21

**Comment by JosephusPaye** [comment] 2019-01-28 10:57
Fix released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).

**Closed by JosephusPaye** 2019-01-28 10:57 UTC
Labels: bug, fixed
