### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/keen-ui#10] opened 2016-04-21 07:14 UTC
Right now I use the built in, but would be nice if all tooltips are replaced with something similar to this.

https://material.angularjs.org/latest/demo/tooltip

**Comment by JosephusPaye** [comment] 2016-04-22 07:00
Tooltips just landed in 0.8.7: http://josephuspaye.github.io/keen-ui/#/ui-tooltip-docs

**Closed by JosephusPaye** 2016-04-22 07:01 UTC

**Comment by EmilMoe** [comment] 2016-04-22 07:55
Nice implementation and it works out of the box

However it seems that they are ignored on disabled items?

**Comment by JosephusPaye** [comment] 2016-04-23 00:25
Yes, that's by design since disabled buttons do not trigger focus and hover events.
