### ISSUE TITLE
Customizing color

### ISSUE THREAD

**Issue by thepill** [JosephusPaye/Keen-UI#198] opened 2017-02-01 12:57 UTC
i´m tryiing to customzie the colors based on the documentation:

```
module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/dist/',
    filename: 'build.js'
  },
  plugins: [
      new webpack.LoaderOptionsPlugin({
          options: {
              sassLoader: {
                  data: '@import "src/styles/variables.scss";',
                  includePaths: 'src/styles'
              },
              context: path.resolve(__dirname) // your project root
          }
      })
  ],
....
```

variable.scss
```
$brand-primary-color: #7A1523;
$brand-accent-color: #FF4081;
```

index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>vuekeen</title>
      <link rel="stylesheet" href="keen-ui.min.css">
    <style>
    *,
*::before,
*::after {
    box-sizing: border-box;
}

html {
    font-size: 100%;
}
    </style>
  </head>
  <body>
    <div id="app"></div>
    <script src="keen-ui.min.js"></script>
    <script src="/dist/build.js"></script>
  </body>
</html>
```

Unfortunately the colors are not updated
I'm using the vue webpack-simple template.
Am i missing something?

**Comment by JosephusPaye** [comment] 2017-02-02 00:39
When customizing the components, you have to use a root Vue instance, for example in `App.vue`:

```vue
<template>
    <div>
        <ui-button color="primary">Primary button</ui-button>
        <ui-button color="accent">Accent button</ui-button>
    </div>
</template>

<script>
import 'keen-ui/src/bootstrap'; // Required to setup Keen UI, should be imported only once in your project
import UiButton from 'keen-ui/src/UiButton.vue';

export default {
    components: {
        UiButton
    }
}
</script>
```

And you should not link to the already compiled `keen-ui.min.css` and `keen-ui.min.js`.

**Comment by thepill** [comment] 2017-02-02 07:00
thanks - ist working now!

**Comment by thepill** [comment] 2017-02-02 07:19
I have to reopen this.
It is working as expectet in Chrome. Within IE11 its throwing a Syntax error and also webpack build
```

Version: webpack 2.2.1
Time: 3296ms
       Asset    Size  Chunks                    Chunk Names
    build.js  254 kB       0  [emitted]  [big]  main
build.js.map  325 kB       0  [emitted]         main

ERROR in build.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [./~/keen-ui/src/helpers/modality.js:5,0][build.js:9211,47]
```

**Comment by JosephusPaye** [comment] 2017-02-02 07:27
Are you using babel?

**Comment by thepill** [comment] 2017-02-02 07:35
hm it is the vue simple webpack template wich contains the following lines in the webpack config:
```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
```
Actually there is nothing more than your snippet from above in the Project (just some testing)

**Comment by JosephusPaye** [comment] 2017-02-05 08:08
This seems like something wrong with your ES6 -> ES5 setup, since it works in Chrome (which supports most ES6 features), and not in IE. This is also why UglifyJS is throwing a build error, since it doesn't understand ES6.

**Comment by thepill** [comment] 2017-02-06 08:06
could some support me solving this (using vue cli template)? My knowledge about using webpack is far from good....

**Comment by JosephusPaye** [comment] 2017-05-09 01:19
If you still have this problem, try replacing the `exclude` line in your Webpack config for Babel with this:

```js
exclude: /node_modules(?!(\/|\\)keen-ui)/
```

This will exclude all files in `node_modules` from Babel compilation except Keen UI files.

Closing now. Reopen if you try this and still have the problem.

**Closed by JosephusPaye** 2017-05-09 01:19 UTC
Labels: question

**Comment by necevil** [comment] 2017-05-11 22:44
@thepill did you find a solution to this?
I am also using the Vue CLI Webpack boiler plate (although I am not using the webpack simple).
Things work as intended in dev, but when I build I get the same error you had.

ERROR in static/js/vendor.42ae2e45b1fed6fefc4d.js from UglifyJs
Unexpected token: punc ()) [./~/keen-ui/src/helpers/modality.js:5,0][static/js/vendor.42ae2e45b1fed6fefc4d.js:22408,47]

I figured I would see if you sorted it out.
Will post my solution here if I come up with one before I hear back.
