### ISSUE TITLE
Uncaught TypeError:  Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by pavinthan** [JosephusPaye/Keen-UI#341] opened 2017-06-26 14:24 UTC
Cannot read property 'contains' of undefined
    at a.restrictFocus (keen-ui.min.js:14)
    at HTMLDocument.n (vue.min.js:6)

restrictFocus: function(t) {
                    this.$refs.container.contains(t.target) || (t.stopPropagation(),
                    this.$refs.container.focus())
                },

**Comment by JosephusPaye** [comment] 2017-09-03 11:50
Possible duplicate of https://github.com/JosephusPaye/Keen-UI/issues/318.

**Closed by JosephusPaye** 2017-09-03 11:50 UTC
